name: Check Wording
on:
  push:
    paths:
    - 'website/docs/**'

jobs:
  prose:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@reviewdog
        with:
        # Optional
          files: '["website/docs"]'
        env:
          # Required
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}